### ISSUE TITLE
styles used in markdown not implemented or incorrect

### ISSUE THREAD

**Issue by pferrel** [actionml/docs.actionml.com#1]
I have one doc ready to go with use of strong and ul/li elements. The Strong should be bold, the ul/li should be bulleted. Seems like we need the basic markdown supported styles implemented. This is a shot of /docs/welcome_to_actionml.md.

@hitgirl do we have the basic markdown elements speced?

![image](https://cloud.githubusercontent.com/assets/326731/15002553/233707a8-1157-11e6-936b-2147a1225175.png)

**Comment by hitgirl** [comment]
No spec. @pote, what flavor of markdown does it support?

**Comment by pote** [comment]
Updated styles are live! Check out the same page now: http://dev.actionml.com/docs/welcome_to_actionml

**Comment by pferrel** [comment]
much better. I'll put up an example of all legal md styles on the blog and docs.
