### ISSUE TITLE
"no route on the client" error

### ISSUE THREAD

**Issue by alex9311** [actionml/docs.actionml.com#10]
Links to [http://actionml.com/docs](http://actionml.com/docs) don't seem to be working.

Noticed someone else mentioned the same problem on the [predictionio forum](https://groups.google.com/forum/#!topic/predictionio-user/iYj5gnuZJs8)

wasn't sure where the best place to report this was, but there ya go

<img width="637" alt="screen shot 2016-06-13 at 3 13 14 pm" src="https://cloud.githubusercontent.com/assets/1326899/16008668/6225cc32-3179-11e6-9f77-865e335d284a.png">

**Comment by pferrel** [comment]
Works for me, are you seeing this?

Try deleting your browser cache or trying a different browser. If this doesn't clear it up can you describe your machine, os, and browser? Looks like Chrome?

**Comment by alex9311** [comment]
My mistake for not checking thoroughly. It works fine in firefox but not in chrome.

For chrome I tried clearing the cache and an incognito window, neither worked. 

Chrome Version 51.0.2704.84 (64-bit)
OS X El Capitan 10.11.4

**Comment by pferrel** [comment]
I've seen similar things with Chrome myself but somehow got out of the problem by hitting refresh several times, or going to the front page and navigating to the docs section, and/or clearing the cache. Once I got it cleared up it stayed clear. After trying all this if you see any errors in the developers console let me know but in my case it was a Chrome problem.

**Comment by alex9311** [comment]
hey pat,

I've tried refreshing a few times and navigating from the homepage but it is still giving me the same error. I also noticed that [http://actionml.com/universal-recommender](http://actionml.com/universal-recommender) and [http://actionml.com/about](http://actionml.com/about) have the same problem. 

Still specific to chrome only, so its not urgent or of course.

**Comment by pferrel** [comment]
Chrome made a javascript change that broke things, I have tried the official work-around so could you try the site again?

**Comment by alex9311** [comment]
Hey Pat,

Looks good to me now! 

Thanks for quick responses and quick fix

Cheers
